language: coq
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
after_success:
  - make html
env:
  - PACKAGE=sou-ken-topos OCAML_VERSION=4.06
os:
  - linux
  - osx
deploy:
  provider: pages
  target-branch: gh-pages
  local-dir: html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: yoshihiro503/travis-ci
